
services:
  garage:
    image: dxflrs/garage:v1.0.0
    restart: unless-stopped
    ports:
      - 3900:3900
    volumes:
      - ./garage.toml:/etc/garage.toml:ro,z

  aasa_assetlinks_service_0: &aasa_assetlinks_service
    restart: unless-stopped
    build:
      context: .
    ports:
      - 4000:4000
    env_file:
      - .env
    environment: &aasa_assetlinks_service_env
      NODE_HOST: aasa_assetlinks_service_0
      CLUSTERING_STRATEGY: gossip
      RELEASE_DISTRIBUTION: sname
      S3_REGION: garage
      S3_PORT: 3900
      S3_HOST: garage
      S3_URL_SCHEME: http
      S3_BUCKET_NAME: aasa-assetlinks

  aasa_assetlinks_service_1:
    <<: *aasa_assetlinks_service
    ports: []
    environment:
      <<: *aasa_assetlinks_service_env
      NODE_HOST: aasa_assetlinks_service_1

  aasa_assetlinks_service_2:
    <<: *aasa_assetlinks_service
    ports: []
    environment:
      <<: *aasa_assetlinks_service_env
      NODE_HOST: aasa_assetlinks_service_2
