---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aasa-assetlinks-server
  labels:
    app.kubernetes.io/name: aasa-assetlinks-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: aasa-assetlinks-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aasa-assetlinks-server
    spec:
      containers:
      - name: aasa-assetlinks-server
        image: ghcr.io/xshadowlegendx/aasa-assetlinks-server:latest
        resources:
          limits:
            cpu: 384m
            memory: 256Mi
        ports:
        - name: http
          containerPort: 4000
        env:
        - name: CLUSTERING_STRATEGY
          value: k8s
        - name: CLUSTERING_STRATEGY_K8S_HEADLESS_SERVICE_NAME
          value: aasa-assetlinks-server-headless.default.svc.cluster.local
        - name: RELEASE_DISTRIBUTION
          value: name
        - name: NODE_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        envFrom:
        - secretRef:
            name: aasa-assetlinks-server

---
apiVersion: v1
kind: Service
metadata:
  name: aasa-assetlinks-server
  labels:
    app.kubernetes.io/name: aasa-assetlinks-server
spec:
  selector:
    app.kubernetes.io/name: aasa-assetlinks-server
  ports:
  - port: 80
    targetPort: http

---
apiVersion: v1
kind: Service
metadata:
  name: aasa-assetlinks-server-headless
  labels:
    app.kubernetes.io/name: aasa-assetlinks-server
spec:
  selector:
    app.kubernetes.io/name: aasa-assetlinks-server

---
apiVersion: v1
kind: Secret
metadata:
  name: aasa-assetlinks-server
  labels:
    app.kubernetes.io/name: aasa-assetlinks-server
data: {}
